import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop/ScrollToTop";
import WhatsappWidget from "@/components/WhatsappWidget/WhatsappWidget";
import Navbar from "@/components/NavBar/Navbar";
import Footer from "@/components/Footer/Footer";
import TopBanner from "@/components/TopBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Q9 Labs",
  description: "Generated by create next app",
  // icons: {
  //   icon: '/favicon-black.png',
  // },
  icons: {
    icon: [
      {
        url: "/favicon-black.png",
        media: "(prefers-color-scheme: light)", // shows on light theme
      },
      {
        url: "/favicon-white.png",
        media: "(prefers-color-scheme: dark)", // shows on dark theme
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <TopBanner />

        <Navbar />

        {children}
        <ScrollToTop />
        <WhatsappWidget />

        <Footer />
      </body>
    </html>
  );
}
